name: CI
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: gem install xcpretty
      - run: |
          set -o pipefail && xcodebuild test -enableCodeCoverage YES \
          -scheme OpenMensaInfrastructure  \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13' \
          ONLY_ACTIVE_ARCH=NO | xcpretty        
      
